<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="gps_length" value="0.1"/>
    <xacro:property name="gps_width" value="0.1"/>
    <xacro:property name="gps_height" value="0.005"/>
    
    
    
    <link name="gps_link">
        <visual>
            <geometry>
                <box size="${gps_length} ${gps_width} ${gps_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${gps_length} ${gps_width} ${gps_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia m="0.05" l="${2* gps_length}" w="${2*gps_width}" h="${2*gps_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_gps" type="fixed">
        <parent link="base_link"/>
        <child link="gps_link"/>
        <origin xyz="${-2 * imu_length} 0.0 ${body_height + gps_height/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="gps_link">
        <material>
            Gazebo/Red
        </material>
        <gravity>true</gravity>
        <sensor name="my_gps" type="gps">
            <!-- ensure the sensor is active (required) -->
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <plugin name="my_gps_plugin" filename="libgazebo_ros_gps_sensor.so">
              <ros>
                <!-- publish to /gps/data -->
                <remapping>~/out:=gps_data</remapping>
                <remapping>~/vel:=gps_velocity</remapping>
              </ros>
            </plugin>
          </sensor>
    </gazebo>
    

</robot>