<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="imu_length" value="0.1"/>
    <xacro:property name="imu_width" value="0.1"/>
    <xacro:property name="imu_height" value="0.005"/>
    
    
    
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia m="0.05" l="${2* imu_length}" w="${2*imu_width}" h="${2*imu_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_imu" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.0 0.0 ${body_height + imu_height/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="imu_link">
        <material>
            Gazebo/Red
        </material>
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
          <always_on>true</always_on>
          <update_rate>50</update_rate>
          <visualize>true</visualize>
          <topic>imu_topic</topic>
          <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_publisher">
            <ros>
                <!-- publish to /imu/data -->
                <remapping>~/out:=imu_data</remapping>
            </ros>
            <topicName>imu</topicName>
            <bodyName>imu_link</bodyName>
            <updateRateHZ>10.0</updateRateHZ>
            <gaussianNoise>0.0</gaussianNoise>
            <xyzOffset>0 0 0</xyzOffset>
            <rpyOffset>0 0 0</rpyOffset>
            <frameName>imu_link</frameName>
            <initialOrientationAsReference>false</initialOrientationAsReference>
          </plugin>
          <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>
    

</robot>