<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="body_length" value="0.8"/>
    <xacro:property name="body_width" value="0.5"/>
    <xacro:property name="body_height" value="0.25"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>


    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${body_height / 2}" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${body_height / 2}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia m="5.0" l="${2* body_length}" w="${2*body_width}" h="${2*body_height}"
                           xyz="0 0 ${body_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2 * wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right_top"/>
    <xacro:wheel_link prefix="right_down"/>
    <xacro:wheel_link prefix="left_top"/>
    <xacro:wheel_link prefix="left_down"/>

    <link name="base_footprint"/>
    
    <joint name="base_base" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
    </joint>
    


    <joint name="base_right_top" type="continuous">
        <parent link="base_link"/>
        <child link="right_top_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${body_length / 4.0} ${-(body_width + wheel_length) / 2.0} 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
    </joint>
    
    <joint name="base_left_top" type="continuous">
        <parent link="base_link"/>
        <child link="left_top_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${body_length / 4.0} ${(body_width + wheel_length) / 2.0} 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
    </joint>

    <joint name="base_right_down" type="continuous">
        <parent link="base_link"/>
        <child link="right_down_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-body_length / 4.0} ${-(body_width + wheel_length) / 2.0} 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
    </joint>

    <joint name="base_left_down" type="continuous">
        <parent link="base_link"/>
        <child link="left_down_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-body_length / 4.0} ${(body_width + wheel_length) / 2.0} 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
    </joint>

</robot>